function comparison = make_peak_guard_pair_comparison(strategyMetrics)
%MAKE_PEAK_GUARD_PAIR_COMPARISON Compare paired VPP-BM and Peak Guard rows.
%   Only complete, successful pairs are returned. Savings sacrifices are
%   kept in their explicitly named paper-load and PV-self engineering
%   denominators; they are never interchanged.

arguments
    strategyMetrics table
end

requiredVariables = ["Dataset", "Day", "Strategy", "Status", ...
    "PeakGuardCapKW", "PaperSavingsPercent", ...
    "EngineeringSavingsPercent", "OptimizedBillEUR", "AllDayPeakKW", ...
    "DaytimePeakKW", "LoadRangeKW", "TotalGridImportKWh", ...
    "BatteryThroughputKWh", "PvCurtailmentKWh", ...
    "EnergyBalanceResidualKW", "TerminalSocErrorKWh", ...
    "SimultaneousChargeDischargeKW"];
missingVariables = requiredVariables(~ismember(requiredVariables, ...
    string(strategyMetrics.Properties.VariableNames)));
if ~isempty(missingVariables)
    error("StoreNet:InvalidPeakGuardMetrics", ...
        "Strategy metrics are missing variable(s): %s.", ...
        strjoin(missingVariables, ", "));
end

strategyMetrics.Dataset = string(strategyMetrics.Dataset);
strategyMetrics.Strategy = string(strategyMetrics.Strategy);
strategyMetrics.Status = string(strategyMetrics.Status);
validateStrategyNames(strategyMetrics.Strategy);

keys = unique(strategyMetrics(:, ["Dataset", "Day"]), "rows", "stable");
rows = repmat(emptyComparisonRow(), 0, 1);
for keyIndex = 1:height(keys)
    selected = strategyMetrics.Dataset == keys.Dataset(keyIndex) & ...
        strategyMetrics.Day == keys.Day(keyIndex);
    pair = strategyMetrics(selected, :);
    vpp = pair(pair.Strategy == "VPP_BM", :);
    peakGuard = pair(pair.Strategy == "IMPROVED_PEAK_GUARD", :);
    if height(vpp) > 1 || height(peakGuard) > 1
        error("StoreNet:InvalidPeakGuardPair", ...
            "Each Dataset/Day requires exactly one VPP_BM and one " + ...
            "IMPROVED_PEAK_GUARD row.");
    end
    if isempty(vpp) || isempty(peakGuard)
        continue
    end
    if vpp.Status ~= "ok" || peakGuard.Status ~= "ok"
        continue
    end
    rows(end + 1, 1) = comparisonRow(vpp, peakGuard); %#ok<AGROW>
end
comparison = struct2table(rows);
end

function validateStrategyNames(strategies)
allowed = ["VPP_BM", "IMPROVED_PEAK_GUARD"];
unexpected = unique(strategies(~ismember(strategies, allowed)));
if ~isempty(unexpected)
    error("StoreNet:InvalidPeakGuardStrategy", ...
        "Unexpected strategy row(s): %s.", strjoin(unexpected, ", "));
end
end

function row = comparisonRow(vpp, peakGuard)
capKW = finiteMatchingCap(vpp.PeakGuardCapKW, peakGuard.PeakGuardCapKW);
row = emptyComparisonRow();
row.Dataset = vpp.Dataset;
row.Day = vpp.Day;
row.PeakGuardCapKW = capKW;
row.VppBillEUR = vpp.OptimizedBillEUR;
row.PeakGuardBillEUR = peakGuard.OptimizedBillEUR;
row.BillPenaltyEUR = peakGuard.OptimizedBillEUR - vpp.OptimizedBillEUR;
row.BillPenaltyPercentOfVpp = safePercent( ...
    row.BillPenaltyEUR, vpp.OptimizedBillEUR);
row.VppPaperSavingsPercent = vpp.PaperSavingsPercent;
row.PeakGuardPaperSavingsPercent = peakGuard.PaperSavingsPercent;
row.PaperSavingsSacrificePercentagePoints = ...
    vpp.PaperSavingsPercent - peakGuard.PaperSavingsPercent;
row.VppEngineeringSavingsPercent = vpp.EngineeringSavingsPercent;
row.PeakGuardEngineeringSavingsPercent = ...
    peakGuard.EngineeringSavingsPercent;
row.EngineeringSavingsSacrificePercentagePoints = ...
    vpp.EngineeringSavingsPercent - peakGuard.EngineeringSavingsPercent;
row.VppAllDayPeakKW = vpp.AllDayPeakKW;
row.PeakGuardAllDayPeakKW = peakGuard.AllDayPeakKW;
row.PeakReductionKW = vpp.AllDayPeakKW - peakGuard.AllDayPeakKW;
row.PeakReductionPercent = safePercent(row.PeakReductionKW, ...
    vpp.AllDayPeakKW);
row.VppPeakExcessOverCapKW = vpp.AllDayPeakKW - capKW;
row.PeakGuardPeakExcessOverCapKW = peakGuard.AllDayPeakKW - capKW;
row.PeakGuardCapViolationKW = max(0, row.PeakGuardPeakExcessOverCapKW);
row.VppCreatesNewPeak = row.VppPeakExcessOverCapKW > 1e-6;
row.PeakGuardCapSatisfied = row.PeakGuardCapViolationKW <= 1e-6;
row.VppDaytimePeakKW = vpp.DaytimePeakKW;
row.PeakGuardDaytimePeakKW = peakGuard.DaytimePeakKW;
row.DaytimePeakChangeKW = peakGuard.DaytimePeakKW - vpp.DaytimePeakKW;
row.VppLoadRangeKW = vpp.LoadRangeKW;
row.PeakGuardLoadRangeKW = peakGuard.LoadRangeKW;
row.LoadRangeReductionKW = vpp.LoadRangeKW - peakGuard.LoadRangeKW;
row.VppGridImportKWh = vpp.TotalGridImportKWh;
row.PeakGuardGridImportKWh = peakGuard.TotalGridImportKWh;
row.GridImportChangeKWh = peakGuard.TotalGridImportKWh - ...
    vpp.TotalGridImportKWh;
row.VppBatteryThroughputKWh = vpp.BatteryThroughputKWh;
row.PeakGuardBatteryThroughputKWh = peakGuard.BatteryThroughputKWh;
row.BatteryThroughputChangeKWh = peakGuard.BatteryThroughputKWh - ...
    vpp.BatteryThroughputKWh;
row.VppPvCurtailmentKWh = vpp.PvCurtailmentKWh;
row.PeakGuardPvCurtailmentKWh = peakGuard.PvCurtailmentKWh;
row.PvCurtailmentChangeKWh = peakGuard.PvCurtailmentKWh - ...
    vpp.PvCurtailmentKWh;
row.VppEnergyBalanceResidualKW = vpp.EnergyBalanceResidualKW;
row.PeakGuardEnergyBalanceResidualKW = ...
    peakGuard.EnergyBalanceResidualKW;
row.VppTerminalSocErrorKWh = vpp.TerminalSocErrorKWh;
row.PeakGuardTerminalSocErrorKWh = peakGuard.TerminalSocErrorKWh;
row.VppSimultaneousChargeDischargeKW = ...
    vpp.SimultaneousChargeDischargeKW;
row.PeakGuardSimultaneousChargeDischargeKW = ...
    peakGuard.SimultaneousChargeDischargeKW;
end

function capKW = finiteMatchingCap(vppCapKW, peakGuardCapKW)
capKW = double(vppCapKW);
otherCapKW = double(peakGuardCapKW);
if ~isscalar(capKW) || ~isscalar(otherCapKW) || ...
        ~isfinite(capKW) || ~isfinite(otherCapKW)
    error("StoreNet:InvalidPeakGuardCap", ...
        "Both rows in a successful pair require a finite cap.");
end
toleranceKW = 1e-10 .* max(1, abs(capKW));
if any(abs(capKW - otherCapKW) > toleranceKW, "all")
    error("StoreNet:PeakGuardCapMismatch", ...
        "VPP and Peak Guard rows do not share the same frozen cap.");
end
end

function value = safePercent(numerator, denominator)
if abs(denominator) <= eps(max(1, abs(denominator)))
    value = NaN;
else
    value = 100 .* numerator ./ denominator;
end
end

function row = emptyComparisonRow()
row = struct( ...
    "Dataset", "", "Day", NaT, "PeakGuardCapKW", NaN, ...
    "VppBillEUR", NaN, "PeakGuardBillEUR", NaN, ...
    "BillPenaltyEUR", NaN, "BillPenaltyPercentOfVpp", NaN, ...
    "VppPaperSavingsPercent", NaN, ...
    "PeakGuardPaperSavingsPercent", NaN, ...
    "PaperSavingsSacrificePercentagePoints", NaN, ...
    "VppEngineeringSavingsPercent", NaN, ...
    "PeakGuardEngineeringSavingsPercent", NaN, ...
    "EngineeringSavingsSacrificePercentagePoints", NaN, ...
    "VppAllDayPeakKW", NaN, "PeakGuardAllDayPeakKW", NaN, ...
    "PeakReductionKW", NaN, "PeakReductionPercent", NaN, ...
    "VppPeakExcessOverCapKW", NaN, ...
    "PeakGuardPeakExcessOverCapKW", NaN, ...
    "PeakGuardCapViolationKW", NaN, "VppCreatesNewPeak", false, ...
    "PeakGuardCapSatisfied", false, "VppDaytimePeakKW", NaN, ...
    "PeakGuardDaytimePeakKW", NaN, "DaytimePeakChangeKW", NaN, ...
    "VppLoadRangeKW", NaN, "PeakGuardLoadRangeKW", NaN, ...
    "LoadRangeReductionKW", NaN, "VppGridImportKWh", NaN, ...
    "PeakGuardGridImportKWh", NaN, "GridImportChangeKWh", NaN, ...
    "VppBatteryThroughputKWh", NaN, ...
    "PeakGuardBatteryThroughputKWh", NaN, ...
    "BatteryThroughputChangeKWh", NaN, ...
    "VppPvCurtailmentKWh", NaN, "PeakGuardPvCurtailmentKWh", NaN, ...
    "PvCurtailmentChangeKWh", NaN, ...
    "VppEnergyBalanceResidualKW", NaN, ...
    "PeakGuardEnergyBalanceResidualKW", NaN, ...
    "VppTerminalSocErrorKWh", NaN, ...
    "PeakGuardTerminalSocErrorKWh", NaN, ...
    "VppSimultaneousChargeDischargeKW", NaN, ...
    "PeakGuardSimultaneousChargeDischargeKW", NaN);
end
