function run = run_bahloul_formal_v1(options)
%RUN_BAHLOUL_FORMAL_V1 Execute the fail-closed B2022-IR-v1 formal matrix.
%   Preflight evidence is written outside the formal root. The formal root
%   is created only after every admission gate passes, and is never reused.

arguments
    options.RepositoryRoot (1, 1) string = ""
    options.FormalRoot (1, 1) string = ""
    options.StagingRoot (1, 1) string = ""
    options.DataRoot (1, 1) string = ""
    options.H4DiagnosticsPath (1, 1) string = ""
    options.DataContractPath (1, 1) string = ""
    options.ModelContractPath (1, 1) string = ""
    options.ReferenceManifestPath (1, 1) string = ""
    options.ReleaseManifestPath (1, 1) string = ""
    options.Figure6EvidenceDirectory (1, 1) string = ""
    options.Figure7ReuseCsv (1, 1) string = ""
    options.Figure7ReuseManifestPath (1, 1) string = ""
    options.ExistingDailyMetricsPath (1, 1) string = ""
    options.ExistingDailyManifestPath (1, 1) string = ""
    options.PreflightRunner (1, 1) function_handle = ...
        @run_bahloul_preflight_v1
    options.TypicalRunner (1, 1) function_handle = ...
        @run_bahloul_typical_v1
    options.MonthlyRunner (1, 1) function_handle = ...
        @run_bahloul_monthly_v1
    options.SensitivityRunner (1, 1) function_handle = ...
        @run_bahloul_sensitivity_v1
    options.AcceptanceEvaluator (1, 1) function_handle = ...
        @evaluate_bahloul_acceptance_v1
    options.Solver (1, 1) function_handle = @solve_storenet
    options.DataProvider (1, 1) function_handle = @load_storenet_day
    options.EnforceCanonicalCallbacks (1, 1) logical = true
    options.FigureVisible (1, 1) logical = false
end

sourceFolder = string(fileparts(mfilename("fullpath")));
if strlength(options.RepositoryRoot) == 0
    options.RepositoryRoot = discoverRepositoryRoot(sourceFolder);
end
root = strip(options.RepositoryRoot);
storeNetRoot = string(fullfile(root, "StoreNet"));
if strlength(options.FormalRoot) == 0
    options.FormalRoot = fullfile(storeNetRoot, "results", ...
        "b2022_ir_v1_formal");
end
if strlength(options.StagingRoot) == 0
    options.StagingRoot = fullfile(storeNetRoot, "tmp", ...
        "b2022_ir_v1_preflight_" + ...
        string(datetime("now"), "yyyyMMdd_HHmmss_SSS"));
end
if strlength(options.DataRoot) == 0
    options.DataRoot = fullfile(storeNetRoot, "data", "raw");
end
if strlength(options.H4DiagnosticsPath) == 0
    options.H4DiagnosticsPath = fullfile(storeNetRoot, "results", ...
        "data_paper_figures_5_10_v2", ...
        "figure6_h4_daily_diagnostics.csv");
end
if strlength(options.DataContractPath) == 0
    options.DataContractPath = fullfile(storeNetRoot, "docs", ...
        "REPRODUCTION_CONTRACT.md");
end
if strlength(options.ModelContractPath) == 0
    options.ModelContractPath = fullfile(storeNetRoot, "docs", ...
        "B2022_REPRODUCTION_CONTRACT.md");
end
if strlength(options.ReferenceManifestPath) == 0
    options.ReferenceManifestPath = fullfile(storeNetRoot, "reference", ...
        "B2022_REFERENCE_MANIFEST.csv");
end
if strlength(options.ReleaseManifestPath) == 0
    options.ReleaseManifestPath = fullfile(storeNetRoot, "data", ...
        "RELEASE_MANIFEST.sha256");
end
if strlength(options.Figure6EvidenceDirectory) == 0
    options.Figure6EvidenceDirectory = fullfile(storeNetRoot, "results", ...
        "data_paper_figures_5_10_v2");
end
if strlength(options.Figure7ReuseCsv) == 0
    options.Figure7ReuseCsv = fullfile(storeNetRoot, "results", ...
        "sensitivity_20200824_vppbm", "sensitivity.csv");
end
if strlength(options.Figure7ReuseManifestPath) == 0
    options.Figure7ReuseManifestPath = fullfile(storeNetRoot, "results", ...
        "sensitivity_20200824_vppbm", "manifest.json");
end
if strlength(options.ExistingDailyMetricsPath) == 0
    options.ExistingDailyMetricsPath = fullfile(storeNetRoot, "results", ...
        "monthly_2020_release_literal_bounded60", "monthly_metrics.csv");
end
if strlength(options.ExistingDailyManifestPath) == 0
    options.ExistingDailyManifestPath = fullfile( ...
        fileparts(options.ExistingDailyMetricsPath), "manifest.json");
end

validateFormalInputBindings(options, root, storeNetRoot);
assertNewFormalRoot(options.FormalRoot);
preflightPath = string(fullfile(options.StagingRoot, ...
    "review_preflight.json"));
if isfile(preflightPath) || isfolder(preflightPath)
    error("StoreNet:PreflightReportExists", ...
        "Refusing to overwrite staging preflight evidence: %s", ...
        preflightPath);
end

preflight = options.PreflightRunner( ...
    RepositoryRoot=root, ReportPath=preflightPath, ...
    FormalOutputPath=options.FormalRoot, ...
    DataContractPath=options.DataContractPath, ...
    ModelContractPath=options.ModelContractPath, ...
    ReferenceManifestPath=options.ReferenceManifestPath, ...
    ReleaseManifestPath=options.ReleaseManifestPath, ...
    Figure6EvidenceDirectory=options.Figure6EvidenceDirectory, ...
    ThrowOnFailure=false, Solver=options.Solver, ...
    DataProvider=options.DataProvider);
validatePassingPreflight(preflight, preflightPath, options);
assertNewFormalRoot(options.FormalRoot);
solverProvenance = actualSolverProvenance(options.Solver, ...
    preflight.gitPreflight);
providerProvenance = actualProviderProvenance(options.DataProvider, ...
    preflight.gitPreflight);
caseProvenance = formalCaseProvenance(preflight, ...
    options.ReferenceManifestPath, solverProvenance, providerProvenance);

[created, message] = mkdir(options.FormalRoot);
if ~created
    error("StoreNet:FormalRootCreateFailed", ...
        "Unable to create formal result root: %s", message);
end

evidenceDirectory = string(fullfile(options.FormalRoot, "evidence"));
mkdir(evidenceDirectory);
preflightEvidencePath = string(fullfile(evidenceDirectory, ...
    "review_preflight.json"));
referenceEvidencePath = string(fullfile(evidenceDirectory, ...
    "B2022_REFERENCE_MANIFEST.csv"));
figure7ReuseEvidencePath = string(fullfile(evidenceDirectory, ...
    "figure7_reuse_source.csv"));
figure7ReuseManifestEvidencePath = string(fullfile(evidenceDirectory, ...
    "figure7_reuse_manifest.json"));
monthlyDailyMetricsEvidencePath = string(fullfile(evidenceDirectory, ...
    "monthly_daily_metrics_source.csv"));
monthlyDailyManifestEvidencePath = string(fullfile(evidenceDirectory, ...
    "monthly_daily_manifest.json"));
copyEvidence(preflightPath, preflightEvidencePath);
copyEvidence(options.ReferenceManifestPath, referenceEvidencePath);
copyEvidence(options.Figure7ReuseCsv, figure7ReuseEvidencePath);
copyEvidence(options.Figure7ReuseManifestPath, ...
    figure7ReuseManifestEvidencePath);
copyEvidence(options.ExistingDailyMetricsPath, ...
    monthlyDailyMetricsEvidencePath);
copyEvidence(options.ExistingDailyManifestPath, ...
    monthlyDailyManifestEvidencePath);

qualityMode = "release_literal";
typicalDay = datetime(2020, 8, 24);
childRunIds = struct( ...
    "typical", "b2022_typical_v1_20200824", ...
    "monthly", "b2022_monthly_v1_2020", ...
    "sensitivity", "b2022_sensitivity_v1_20200824");

typical = options.TypicalRunner(typicalDay, IntervalMinutes=30, ...
    QualityMode=qualityMode, DataRoot=options.DataRoot, ...
    OutputRoot=options.FormalRoot, RunId=childRunIds.typical, ...
    H4DiagnosticsPath=options.H4DiagnosticsPath, ...
    DataProvider=options.DataProvider, Solver=options.Solver, ...
    FigureVisible=options.FigureVisible, PersistSolutions=true, ...
    Provenance=caseProvenance);
validateChildRun(typical, options.FormalRoot, childRunIds.typical, ...
    "typical");

monthly = options.MonthlyRunner(QualityMode=qualityMode, ...
    DataRoot=options.DataRoot, OutputRoot=options.FormalRoot, ...
    RunId=childRunIds.monthly, ...
    H4DiagnosticsPath=options.H4DiagnosticsPath, ...
    DataProvider=options.DataProvider, Solver=options.Solver, ...
    FigureVisible=options.FigureVisible, PersistSolutions=false, ...
    ExistingDailyMetricsPath=monthlyDailyMetricsEvidencePath, ...
    ExistingDailyManifestPath=monthlyDailyManifestEvidencePath, ...
    Provenance=caseProvenance);
validateChildRun(monthly, options.FormalRoot, childRunIds.monthly, ...
    "monthly");

sensitivity = options.SensitivityRunner(typicalDay, ...
    QualityMode=qualityMode, DataRoot=options.DataRoot, ...
    OutputRoot=options.FormalRoot, RunId=childRunIds.sensitivity, ...
    H4DiagnosticsPath=options.H4DiagnosticsPath, ...
    ReuseFigure7Csv=options.Figure7ReuseCsv, ...
    DataProvider=options.DataProvider, Solver=options.Solver, ...
    FigureVisible=options.FigureVisible, Provenance=caseProvenance);
validateChildRun(sensitivity, options.FormalRoot, ...
    childRunIds.sensitivity, "sensitivity");

interpretationPath = writeScientificInterpretation(options.FormalRoot, ...
    typicalDay, qualityMode, childRunIds);

runInfo = formalRunInfo(options, typicalDay, qualityMode, childRunIds, ...
    preflightEvidencePath, referenceEvidencePath, ...
    monthlyDailyMetricsEvidencePath, monthlyDailyManifestEvidencePath, ...
    interpretationPath);
[manifest, manifestPath] = write_run_manifest(options.FormalRoot, ...
    runInfo, FormalMode=true, RepositoryRoot=root, ...
    ReleaseManifestPath=options.ReleaseManifestPath, ...
    DataContractId=string(preflight.contracts.dataContractId), ...
    DataContractSha256=string(preflight.contracts.dataContractSha256), ...
    DataContractGitCommit=string( ...
        preflight.contracts.dataContractGitCommit), ...
    ModelContractId=string(preflight.contracts.modelContractId), ...
    ModelContractSha256=string( ...
        preflight.contracts.modelContractSha256), ...
    ReferenceManifestSha256=string( ...
        preflight.references.manifestSha256), ...
    SolverProvenance=solverProvenance, ...
    DataProviderProvenance=providerProvenance, ...
    GitPreflight=preflight.gitPreflight);
scientificClosure = write_result_manifest_sha256(options.FormalRoot, ...
    FileName="SCIENTIFIC_ARTIFACT_MANIFEST.sha256");
acceptance = options.AcceptanceEvaluator(options.FormalRoot);
closure = write_result_manifest_sha256(options.FormalRoot);
validatePassingAcceptance(acceptance, options.FormalRoot);

run = struct;
run.runType = "B2022-IR-v1_formal";
run.formalRoot = options.FormalRoot;
run.stagingRoot = options.StagingRoot;
run.preflight = preflight;
run.preflightEvidencePath = preflightEvidencePath;
run.referenceEvidencePath = referenceEvidencePath;
run.figure7ReuseEvidencePath = figure7ReuseEvidencePath;
run.figure7ReuseManifestEvidencePath = figure7ReuseManifestEvidencePath;
run.existingDailyMetricsPath = options.ExistingDailyMetricsPath;
run.existingDailyManifestPath = options.ExistingDailyManifestPath;
run.monthlyDailyMetricsEvidencePath = monthlyDailyMetricsEvidencePath;
run.monthlyDailyManifestEvidencePath = monthlyDailyManifestEvidencePath;
run.interpretationPath = interpretationPath;
run.caseProvenance = caseProvenance;
run.childRunIds = childRunIds;
run.children = struct("typical", typical, "monthly", monthly, ...
    "sensitivity", sensitivity);
run.manifest = manifest;
run.manifestPath = string(manifestPath);
run.scientificClosure = scientificClosure;
run.closure = closure;
run.acceptance = acceptance;
end

function validateFormalInputBindings(options, repositoryRoot, storeNetRoot)
requiredFolders = [ ...
    options.DataRoot, options.Figure6EvidenceDirectory];
for folderIndex = 1:numel(requiredFolders)
    if ~isfolder(requiredFolders(folderIndex))
        error("StoreNet:FormalInputBindingMissing", ...
            "Required formal input directory is missing: %s", ...
            requiredFolders(folderIndex));
    end
end
requiredFiles = [options.H4DiagnosticsPath, options.DataContractPath, ...
    options.ModelContractPath, options.ReferenceManifestPath, ...
    options.ReleaseManifestPath, options.Figure7ReuseCsv, ...
    options.Figure7ReuseManifestPath, options.ExistingDailyMetricsPath, ...
    options.ExistingDailyManifestPath];
for fileIndex = 1:numel(requiredFiles)
    if ~isfile(requiredFiles(fileIndex))
        error("StoreNet:FormalInputBindingMissing", ...
            "Required formal input file is missing: %s", ...
            requiredFiles(fileIndex));
    end
end

expectedFolders = [fullfile(storeNetRoot, "data", "raw"), ...
    fullfile(storeNetRoot, "results", "data_paper_figures_5_10_v2")];
for folderIndex = 1:numel(expectedFolders)
    if canonicalExistingFolder(requiredFolders(folderIndex)) ~= ...
            canonicalExistingFolder(expectedFolders(folderIndex))
        error("StoreNet:FormalInputBindingMismatch", ...
            "Formal input directory is not the canonical repository asset: %s", ...
            requiredFolders(folderIndex));
    end
end
expectedFiles = [ ...
    fullfile(expectedFolders(2), "figure6_h4_daily_diagnostics.csv"), ...
    fullfile(storeNetRoot, "docs", "REPRODUCTION_CONTRACT.md"), ...
    fullfile(storeNetRoot, "docs", "B2022_REPRODUCTION_CONTRACT.md"), ...
    fullfile(storeNetRoot, "reference", "B2022_REFERENCE_MANIFEST.csv"), ...
    fullfile(storeNetRoot, "data", "RELEASE_MANIFEST.sha256"), ...
    fullfile(storeNetRoot, "results", "sensitivity_20200824_vppbm", ...
        "sensitivity.csv"), ...
    fullfile(storeNetRoot, "results", "sensitivity_20200824_vppbm", ...
        "manifest.json"), ...
    fullfile(storeNetRoot, "results", ...
        "monthly_2020_release_literal_bounded60", "monthly_metrics.csv"), ...
    fullfile(storeNetRoot, "results", ...
        "monthly_2020_release_literal_bounded60", "manifest.json")];
for fileIndex = 1:numel(expectedFiles)
    if canonicalExistingFile(requiredFiles(fileIndex)) ~= ...
            canonicalExistingFile(expectedFiles(fileIndex))
        error("StoreNet:FormalInputBindingMismatch", ...
            "Formal input file is not the canonical repository asset: %s", ...
            requiredFiles(fileIndex));
    end
end

if options.EnforceCanonicalCallbacks
    callbacks = [string(func2str(options.PreflightRunner)), ...
        string(func2str(options.TypicalRunner)), ...
        string(func2str(options.MonthlyRunner)), ...
        string(func2str(options.SensitivityRunner)), ...
        string(func2str(options.AcceptanceEvaluator)), ...
        string(func2str(options.Solver)), ...
        string(func2str(options.DataProvider))];
    expected = ["run_bahloul_preflight_v1", "run_bahloul_typical_v1", ...
        "run_bahloul_monthly_v1", "run_bahloul_sensitivity_v1", ...
        "evaluate_bahloul_acceptance_v1", "solve_storenet", ...
        "load_storenet_day"];
    if ~isequal(callbacks, expected)
        error("StoreNet:NoncanonicalFormalCallback", ...
            "Formal B2022 execution requires the canonical runner, solver, " + ...
            "provider, and acceptance callbacks.");
    end
end

if canonicalExistingFolder(repositoryRoot) ~= ...
        canonicalExistingFolder(fileparts(storeNetRoot))
    error("StoreNet:FormalRepositoryBindingMismatch", ...
        "StoreNet root is not bound to the requested repository root.");
end
end

function path = canonicalExistingFile(path)
path = string(path);
folder = canonicalExistingFolder(fileparts(path));
[~, name, extension] = fileparts(path);
path = string(fullfile(folder, name + extension));
end

function path = canonicalExistingFolder(path)
original = pwd;
cleaner = onCleanup(@() cd(original));
cd(path);
path = string(pwd);
clear cleaner
end

function path = writeScientificInterpretation(formalRoot, typicalDay, ...
        qualityMode, childRunIds)
path = string(fullfile(formalRoot, "SCIENTIFIC_INTERPRETATION.md"));
if isfile(path) || isfolder(path)
    error("StoreNet:ScientificInterpretationExists", ...
        "Refusing to overwrite scientific interpretation: %s", path);
end
lines = [ ...
    "# B2022-IR-v1 scientific interpretation"; ...
    ""; ...
    "Status language: independent public-release reproduction."; ...
    ""; ...
    "- PROXY: Figure 5 and observed SB-SC use the preregistered structural and release-side proxy definitions."; ...
    "- NOT EXACT: the run does not claim exact recovery of the paper's private dashboard, original nine-PV identity, unpublished typical day, or proprietary SB-SC controller."; ...
    "- NO POST-SOLVE TUNING: date, cohorts, PV boundary, transfer loss, strategy matrix, objective order, and tolerances were frozen before the formal solve."; ...
    "- Paper values are discrepancy anchors only and are not acceptance thresholds."; ...
    ""; ...
    "Frozen typical day: " + string(typicalDay, "yyyy-MM-dd"); ...
    "Frozen quality mode: " + qualityMode; ...
    "Child run IDs: " + strjoin(string(struct2cell(childRunIds)), ", ")];
temporaryPath = string(tempname(formalRoot)) + ".md";
writelines(lines, temporaryPath);
[moved, message] = movefile(temporaryPath, path);
if ~moved
    if isfile(temporaryPath)
        delete(temporaryPath);
    end
    error("StoreNet:ScientificInterpretationWriteFailed", ...
        "Unable to finalize scientific interpretation: %s", message);
end
end

function validatePassingAcceptance(acceptance, formalRoot)
if ~isstruct(acceptance) || ~isscalar(acceptance) || ...
        ~isfield(acceptance, "allRulesPassed") || ...
        ~isscalar(acceptance.allRulesPassed)
    error("StoreNet:InvalidBahloulAcceptance", ...
        "Acceptance evaluator must return allRulesPassed as a scalar.");
end
if ~logical(acceptance.allRulesPassed)
    evidence = string(fullfile(formalRoot, "postsolve_acceptance.json"));
    error("StoreNet:BahloulPostsolveAcceptanceFailed", ...
        "B2022 formal results failed R1--R8 acceptance. Evidence: %s", ...
        evidence);
end
end

function validatePassingPreflight(report, reportPath, options)
if ~isstruct(report) || ~isscalar(report) || ...
        ~isfield(report, "allPassed") || ~isscalar(report.allPassed)
    error("StoreNet:InvalidBahloulPreflight", ...
        "Preflight runner must return a scalar report with allPassed.");
end
if ~logical(report.allPassed)
    error("StoreNet:BahloulPreflightFailed", ...
        "B2022 formal execution is forbidden because preflight did not pass.");
end
if ~isfile(reportPath)
    error("StoreNet:PreflightEvidenceMissing", ...
        "Passing preflight did not persist its review evidence: %s", ...
        reportPath);
end
required = ["contracts", "references", "gitPreflight", ...
    "formalOutputWasAbsent"];
missing = required(~isfield(report, cellstr(required)));
if ~isempty(missing)
    error("StoreNet:InvalidBahloulPreflight", ...
        "Passing preflight is missing field(s): %s", strjoin(missing, ", "));
end
if ~logical(report.formalOutputWasAbsent)
    error("StoreNet:FormalOutputExists", ...
        "Preflight did not establish that the formal root was absent.");
end

requiredContracts = ["dataContractId", "dataContractSha256", ...
    "dataContractGitCommit", "modelContractId", ...
    "modelContractSha256"];
missingContracts = requiredContracts(~isfield(report.contracts, ...
    cellstr(requiredContracts)));
if ~isempty(missingContracts) || ...
        ~isfield(report.references, "manifestSha256")
    error("StoreNet:InvalidBahloulPreflight", ...
        "Passing preflight lacks contract or reference provenance.");
end
if string(report.contracts.dataContractId) ~= "SR2020-IR-v2" || ...
        string(report.contracts.modelContractId) ~= "B2022-IR-v1"
    error("StoreNet:FormalContractIdMismatch", ...
        "Formal execution requires SR2020-IR-v2 and B2022-IR-v1.");
end

verifyReportedHash(options.DataContractPath, ...
    report.contracts.dataContractSha256, "data contract");
verifyReportedHash(options.ModelContractPath, ...
    report.contracts.modelContractSha256, "model contract");
verifyReportedHash(options.ReferenceManifestPath, ...
    report.references.manifestSha256, "reference manifest");
validateHex(report.contracts.dataContractGitCommit, 40, ...
    "data contract Git commit");
validatePreflightGit(report.gitPreflight, options.RepositoryRoot);
if isfield(report, "reportSha256")
    verifyReportedHash(reportPath, report.reportSha256, ...
        "preflight report");
end
end

function validatePreflightGit(git, repositoryRoot)
required = ["repositoryRoot", "commit", "statusAvailable", "isClean", ...
    "untrackedFilesIncluded", "capturedBeforeOutputDirectory"];
missing = required(~isfield(git, cellstr(required)));
if ~isempty(missing)
    error("StoreNet:InvalidBahloulPreflight", ...
        "Git preflight is missing field(s): %s", strjoin(missing, ", "));
end
if strip(string(git.repositoryRoot)) ~= strip(string(repositoryRoot))
    error("StoreNet:GitPreflightRepositoryMismatch", ...
        "Git preflight repository does not match the formal repository.");
end
validateHex(git.commit, 40, "preflight Git commit");
if ~logical(git.statusAvailable) || ~logical(git.isClean) || ...
        ~logical(git.untrackedFilesIncluded) || ...
        ~logical(git.capturedBeforeOutputDirectory)
    error("StoreNet:InvalidBahloulPreflight", ...
        "Formal Git preflight must be available, clean, complete, and early.");
end
end

function verifyReportedHash(path, reported, label)
validateHex(reported, 64, label + " SHA-256");
observed = sha256File(path);
if observed ~= lower(strip(string(reported)))
    error("StoreNet:FormalEvidenceHashMismatch", ...
        "Runtime %s hash differs from passing preflight evidence.", label);
end
end

function validateHex(value, width, label)
expression = "^[0-9A-Fa-f]{" + width + "}$";
if isempty(regexp(char(strip(string(value))), char(expression), ...
        'once'))
    error("StoreNet:InvalidFormalProvenance", ...
        "%s must contain exactly %d hexadecimal characters.", ...
        label, width);
end
end

function copyEvidence(source, destination)
if ~isfile(source)
    error("StoreNet:FormalEvidenceMissing", ...
        "Required formal evidence is missing: %s", source);
end
if isfile(destination) || isfolder(destination)
    error("StoreNet:FormalEvidenceExists", ...
        "Refusing to overwrite formal evidence: %s", destination);
end
[copied, message] = copyfile(source, destination);
if ~copied
    error("StoreNet:FormalEvidenceCopyFailed", ...
        "Unable to copy formal evidence: %s", message);
end
end

function validateChildRun(child, formalRoot, runId, label)
expectedDirectory = string(fullfile(formalRoot, runId));
if ~isfolder(expectedDirectory)
    error("StoreNet:FormalChildOutputMissing", ...
        "The %s runner did not create its fixed child directory: %s", ...
        label, expectedDirectory);
end
if ~isstruct(child) || ~isscalar(child) || ...
        ~isfield(child, "runDirectory") || ...
        strip(string(child.runDirectory)) ~= strip(expectedDirectory)
    error("StoreNet:FormalChildOutputMismatch", ...
        "The %s runner returned a runDirectory other than %s.", ...
        label, expectedDirectory);
end
end

function info = formalRunInfo(options, typicalDay, qualityMode, ...
        childRunIds, preflightPath, referencePath, ...
        monthlyDailyMetricsEvidencePath, monthlyDailyManifestEvidencePath, ...
        interpretationPath)
info = struct;
info.runType = "B2022-IR-v1_formal";
info.typicalDay = string(typicalDay, "yyyy-MM-dd");
info.typicalIntervalMinutes = 30;
info.qualityMode = qualityMode;
info.dataRoot = options.DataRoot;
info.h4DiagnosticsPath = options.H4DiagnosticsPath;
info.dataContractPath = options.DataContractPath;
info.modelContractPath = options.ModelContractPath;
info.referenceManifestPath = options.ReferenceManifestPath;
info.releaseManifestPath = options.ReleaseManifestPath;
info.figure6EvidenceDirectory = options.Figure6EvidenceDirectory;
info.figure7ReuseCsv = options.Figure7ReuseCsv;
info.figure7ReuseManifestPath = options.Figure7ReuseManifestPath;
info.existingDailyMetricsPath = options.ExistingDailyMetricsPath;
info.existingDailyManifestPath = options.ExistingDailyManifestPath;
info.monthlyDailyMetricsEvidencePath = monthlyDailyMetricsEvidencePath;
info.monthlyDailyManifestEvidencePath = monthlyDailyManifestEvidencePath;
info.canonicalCallbacksEnforced = options.EnforceCanonicalCallbacks;
info.childRunIds = childRunIds;
info.executionOrder = ["typical", "monthly", "sensitivity"];
info.preflightEvidencePath = preflightPath;
info.referenceEvidencePath = referencePath;
info.scientificInterpretationPath = interpretationPath;
end

function provenance = actualSolverProvenance(solver, git)
provenance = struct;
provenance.name = string(func2str(solver));
provenance.interface = "StoreNet MATLAB solver callback";
provenance.version = string(version("-release"));
provenance.matlabVersion = string(version);
provenance.sourceGitCommit = string(git.commit);
optimizationToolbox = ver("optim");
if isempty(optimizationToolbox)
    provenance.optimizationToolboxVersion = "unavailable";
else
    provenance.optimizationToolboxVersion = ...
        string(optimizationToolbox(1).Version);
end
end

function provenance = actualProviderProvenance(provider, git)
provenance = struct;
provenance.name = string(func2str(provider));
provenance.interface = "StoreNet MATLAB data-provider callback";
provenance.matlabVersion = string(version);
provenance.sourceGitCommit = string(git.commit);
end

function provenance = formalCaseProvenance(preflight, referencePath, ...
        solver, provider)
[referenceIds, referenceHashes] = readReferenceInventory(referencePath);
provenance = struct;
provenance.dataContractId = string(preflight.contracts.dataContractId);
provenance.dataContractSha256 = string( ...
    preflight.contracts.dataContractSha256);
provenance.dataContractGitCommit = string( ...
    preflight.contracts.dataContractGitCommit);
provenance.modelContractId = string(preflight.contracts.modelContractId);
provenance.modelContractSha256 = string( ...
    preflight.contracts.modelContractSha256);
provenance.referenceIds = referenceIds;
provenance.referenceHashes = referenceHashes;
provenance.referenceManifestSha256 = string( ...
    preflight.references.manifestSha256);
provenance.solverProvenance = solver;
provenance.dataProviderProvenance = provider;
end

function [ids, hashes] = readReferenceInventory(path)
manifest = readtable(path, Delimiter=",", TextType="string", ...
    VariableNamingRule="preserve");
required = ["ArtifactId", "Sha256"];
missing = required(~ismember(required, ...
    string(manifest.Properties.VariableNames)));
if ~isempty(missing) || height(manifest) == 0
    error("StoreNet:InvalidReferenceManifest", ...
        "Reference manifest lacks ArtifactId/Sha256 inventory rows.");
end
ids = strip(string(manifest.ArtifactId(:)));
hashes = lower(strip(string(manifest.Sha256(:))));
if any(strlength(ids) == 0) || numel(unique(ids)) ~= numel(ids)
    error("StoreNet:InvalidReferenceManifest", ...
        "Reference ArtifactId values must be nonempty and unique.");
end
for hashIndex = 1:numel(hashes)
    validateHex(hashes(hashIndex), 64, ...
        "reference artifact SHA-256");
end
end

function assertNewFormalRoot(path)
if isfolder(path) || isfile(path)
    error("StoreNet:FormalOutputExists", ...
        "Refusing to overwrite existing formal result root: %s", path);
end
end

function hash = sha256File(path)
hash = storenetio.hashFile(path);
end

function root = discoverRepositoryRoot(startFolder)
[status, output] = system("git -C " + shellQuote(startFolder) + ...
    " rev-parse --show-toplevel");
if status ~= 0
    error("StoreNet:RepositoryRootUnavailable", ...
        "Unable to discover the StoreNet repository root.");
end
root = string(strtrim(output));
end

function quoted = shellQuote(value)
quoted = storenetio.shellQuote(value);
end

