classdef TestStoreNetReporting < matlab.unittest.TestCase
    %TESTSTORENETREPORTING Contract tests for monthly comparison reporting.

    properties
        OutputRoot
        LiteralDirectory
        ExcludeDirectory
    end

    methods (TestClassSetup)
        function addSourceFolder(testCase)
            testFolder = fileparts(mfilename("fullpath"));
            sourceFolder = fullfile(fileparts(testFolder), "src");
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                sourceFolder));
        end
    end

    methods (TestMethodSetup)
        function createSyntheticRuns(testCase)
            testCase.OutputRoot = string(tempname);
            mkdir(testCase.OutputRoot);
            testCase.addTeardown(@() rmdir(testCase.OutputRoot, "s"));
            testCase.LiteralDirectory = fullfile(testCase.OutputRoot, "literal");
            testCase.ExcludeDirectory = fullfile(testCase.OutputRoot, "exclude");
            writeSyntheticMonthlyRuns(testCase.LiteralDirectory, ...
                testCase.ExcludeDirectory);
        end
    end

    methods (Test)
        function testWritesAlignedComparisonArtifacts(testCase)
            report = render_monthly_comparison( ...
                testCase.LiteralDirectory, testCase.ExcludeDirectory, ...
                OutputRoot=testCase.OutputRoot, RunId="comparison_unit", ...
                FigureVisible=false);

            testCase.verifyEqual(report.strategyComparison.Strategy, ...
                ["SH_BM"; "VPP_BM"; "PS"; "PSDT"; "LL"]);
            testCase.verifyEqual( ...
                report.strategyComparison.LiteralSuccessfulDays, ...
                [40; 41; 42; 43; 44], AbsTol=1e-12);
            testCase.verifyEqual( ...
                report.strategyComparison.ExcludeSuccessfulDays, ...
                [30; 31; 32; 33; 34], AbsTol=1e-12);
            testCase.verifyEqual( ...
                report.strategyComparison.LiteralMeanSavingsPercent, ...
                [10; 20; 30; 40; 50], AbsTol=1e-12);
            testCase.verifyEqual( ...
                report.strategyComparison.ExcludeMeanPeakImportKW, ...
                [25; 26; 27; 28; 29], AbsTol=1e-12);
            testCase.verifyEqual(report.qualityComparison.Mode, ...
                ["release_literal"; "exclude_flagged_pv"]);
            testCase.verifyEqual(report.qualityComparison.RequestedDays, ...
                [4; 4], AbsTol=1e-12);
            testCase.verifyEqual(report.qualityComparison.PassedDays, ...
                [3; 2], AbsTol=1e-12);
            testCase.verifyEqual(report.qualityComparison.RejectedDays, ...
                [1; 2], AbsTol=1e-12);
            testCase.verifyEqual(report.qualityComparison.SolverFailedRows, ...
                [2; 1], AbsTol=1e-12);
            testCase.verifyTrue(isfile(report.strategyPath));
            testCase.verifyTrue(isfile(report.qualityPath));
            testCase.verifyTrue(isfile(report.figurePath));
            testCase.verifyTrue(isfile(report.manifestPath));
            testCase.verifyEqual(report.manifest.experiment.runType, ...
                "monthly_quality_mode_comparison");
        end

        function testRefusesNonemptyRunDirectory(testCase)
            existingDirectory = fullfile(testCase.OutputRoot, "existing");
            createNonemptyDirectory(existingDirectory);
            invoke = @() render_monthly_comparison( ...
                testCase.LiteralDirectory, testCase.ExcludeDirectory, ...
                OutputRoot=testCase.OutputRoot, RunId="existing", ...
                FigureVisible=false);

            testCase.verifyError(invoke, "StoreNet:RunDirectoryExists");
        end

        function testRejectsIncompleteStrategySet(testCase)
            removeStrategy(testCase.LiteralDirectory, "LL");
            invoke = @() render_monthly_comparison( ...
                testCase.LiteralDirectory, testCase.ExcludeDirectory, ...
                OutputRoot=testCase.OutputRoot, RunId="invalid_strategies", ...
                FigureVisible=false);

            testCase.verifyError(invoke, ...
                "StoreNet:InvalidReportingStrategies");
        end
    end
end

function writeSyntheticMonthlyRuns(literalDirectory, excludeDirectory)
mkdir(literalDirectory);
mkdir(excludeDirectory);
strategy = ["PS"; "SH_BM"; "LL"; "VPP_BM"; "PSDT"];

literalSummary = table(strategy, [42; 40; 44; 41; 43], ...
    48 * ones(5, 1), [30; 10; 50; 20; 40], [32; 30; 34; 31; 33], ...
    [12; 10; 14; 11; 13], VariableNames=["Strategy", ...
    "SuccessfulDays", "RequestedDays", "MeanSavingsPercent", ...
    "MeanPeakImportKW", "MeanOptimizedBillEUR"]);
excludeSummary = table(strategy, [32; 30; 34; 31; 33], ...
    48 * ones(5, 1), [28; 8; 48; 18; 38], [27; 25; 29; 26; 28], ...
    [13; 11; 15; 12; 14], VariableNames=["Strategy", ...
    "SuccessfulDays", "RequestedDays", "MeanSavingsPercent", ...
    "MeanPeakImportKW", "MeanOptimizedBillEUR"]);
writetable(literalSummary, fullfile(literalDirectory, "monthly_summary.csv"));
writetable(excludeSummary, fullfile(excludeDirectory, "monthly_summary.csv"));

qualityDays = datetime(2020, 1, 1:4).';
literalQuality = table(qualityDays, ...
    ["passed"; "passed"; "quality_rejected"; "passed"], ...
    VariableNames=["Day", "Status"]);
excludeQuality = table(qualityDays, ...
    ["passed"; "quality_rejected"; "quality_rejected"; "passed"], ...
    VariableNames=["Day", "Status"]);
writetable(literalQuality, ...
    fullfile(literalDirectory, "monthly_quality_status.csv"));
writetable(excludeQuality, ...
    fullfile(excludeDirectory, "monthly_quality_status.csv"));

metricDays = datetime(2020, 1, 2) + caldays((0:4).');
literalMetrics = table(metricDays, strategy, ...
    ["ok"; "failed"; "ok"; "failed"; "ok"], ...
    VariableNames=["Day", "Strategy", "Status"]);
excludeMetrics = table(metricDays, strategy, ...
    ["ok"; "ok"; "failed"; "ok"; "ok"], ...
    VariableNames=["Day", "Strategy", "Status"]);
writetable(literalMetrics, fullfile(literalDirectory, "monthly_metrics.csv"));
writetable(excludeMetrics, fullfile(excludeDirectory, "monthly_metrics.csv"));
end

function createNonemptyDirectory(directory)
mkdir(directory);
writelines("do not overwrite", fullfile(directory, "marker.txt"));
end

function removeStrategy(directory, strategy)
path = fullfile(directory, "monthly_summary.csv");
summary = readtable(path, TextType="string");
summary(summary.Strategy == strategy, :) = [];
writetable(summary, path);
end
